stages:
  prepare_environment:
    cmd: PYTHONPATH=$(pwd)/src python $(pwd)/src/stages/prepare_environment.py
    deps:
      - src/utility/load.py
      - src/utility/directory.py
      - src/utility/model.py
      - src/utility/device.py
      - src/stages/prepare_environment.py
    params:
      - prepare_environment
      - training
    outs:
      - data/processed/model_summary.txt
      - data/processed/checkpoint 

  preprocess_feedback:
    cmd: PYTHONPATH=$(pwd)/src python $(pwd)/src/stages/preprocess_feedback_data.py
    deps:
      - src/utility/load.py
      - src/utility/directory.py
      - src/utility/video.py
      - src/utility/file.py
      - src/stages/preprocess_feedback.py
    params:
      - preprocess_feedback
      - prepare_environment
    outs:
      - data/interim/merged_train_data.csv
      - data/interim/merged_val_data.csv


  preprocess_data:
    cmd: PYTHONPATH=$(pwd)/src python $(pwd)/src/stages/preprocess_data.py
    deps:
      - src/utility/load.py
      - src/utility/directory.py
      - src/utility/video.py
      - src/utility/file.py
      - src/stages/preprocess_data.py
      - data/interim/merged_train_data.csv
      - data/interim/merged_val_data.csv
    params:
      - preprocess
      - prepare_environment


  train:
    cmd: PYTHONPATH=$(pwd)/src python $(pwd)/src/stages/train.py
    deps:
      - src/utility/load.py
      - src/utility/directory.py
      - src/utility/model.py
      - src/utility/device.py
      - src/stages/train.py
    params:
      - training
      - prepare_environment
      - load_training_data
    outs:
      - data/processed/training.json
      - data/processed/validation.json



