preprocess:
  trim_list_file: 
  output_shape: [224, 224]
  output_file_name: /data/interim/trim_data.pt
  data_aug_flag: True

prepare_environment:
  seed: 42
  cuda_device_id: cuda:0
  model_summary: /data/processed/model_summary.txt
  working_dir: /data/processed
  logs:
  - training_log: training.json
  - validation_log: validation.json
  model:
    file: src/models/dyadic_cnn_3d.py
    class: DyadicCNN3DV2 
    params:
      num_dyads: 4
      in_shape: [3, 90, 224, 224]

load_training_data:
  data_file: /data/interim/trim_data.pt
  batch_size: 32
  shuffle: True
  num_workers: 16

training:
  max_epochs: 100
  epoch_save_interval: 5
  epock_skip: 50
  early_stopping: 5
  input_shape: [3, 90, 224, 224]
  batch_size: 16
  






