preprocess:
  trim_list_file: data/raw/training_data.txt
  val_data: data/raw/val_data.txt
  output_shape: [224, 224]
  output_file_name: data/interim/trim_data.pt
  output_val_file_name: data/interim/trim_val_data.pt
  data_aug_flag: True
  val_data_aug_flag: False
  video_dir: data/processed/one_trim_per_instance_3sec_224

video:
  video_dir: data/raw/videos
  trims_dir: data/processed/one_trim_per_instance_3sec_224

training_data:
  merge_data: True
  merge_dataset_file: data/interim/merged_train_data.csv

validation_data:
  merge_data: True
  merge_dataset_file: data/interim/merged_val_data.csv

preprocess_feedback_data:
  is_feedback: False
  predictions_file_path: data/raw/predictions.csv
  filtered_predictions_file_path: data/interim/filtered_predictions.csv
  prediction_trims_file_path: data/interim/prediction_trims.txt
  video_trims_dir: data/processed
  feedback_trims_list_path: data/interim/feedback_trims_list.csv
  merged_trims_file: data/interim/merged_feedback_data.csv


prepare_environment:
  seed: 42
  cuda_device_id: cuda:0
  model_summary: data/processed/model_summary.txt
  checkpoint: data/external/best_epoch53.pth
  checkpoint_dir: data/processed/checkpoint
  working_dir: data/processed
  logs:
  - training.json
  - validation.json
  model:
    file: src/models/dyadic_cnn_3d.py
    class: DyadicCNN3DV2 
    params:
      num_dyads: 4
      in_shape: [3, 90, 224, 224]

load_training_data:
  data_file: data/interim/trim_data.pt
  batch_size: 32
  shuffle: True
  num_workers: 16
  num_workers_val: 8

training:
  max_epochs: 100
  epoch_save_interval: 5
  epoch_skip: 50
  early_stopping: 10
  input_shape: [3, 90, 224, 224]
  batch_size: 16

validation:
  test_size: 0.2
  






